### ISSUE TITLE
"/usr/lib/osc-plugins/osc-collab.py", line 550     except SyntaxError, e:

### ISSUE THREAD

**Issue by Twoflower2** [openSUSE/osc-plugin-collab#56]
Still fails in Leap 15.2

```
$  osc -A https://api.suse.de api 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9356, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/osc-plugins/osc-collab.py", line 550
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax

/usr/lib/osc-plugins/osc-collab.py: invalid syntax (osc-collab.py, line 550)

 Try 'env OSC_PLUGIN_FAIL_IGNORE=1 osc ...'
```

```
Version: 0.99-lp152.3.2
Provides: osc-plugin-collab = 0.99-lp152.3.2
Requires: rpmlib(CompressedFileNames) <= 3.0.4-1rpmlib(FileDigests) <= 4.6.0-1rpmlib(PayloadFilesHavePrefix) <= 4.0-1rpmlib(PayloadIsXz) <= 5.2-1osc >= 0.140.1
Conflicts: osc-plugins-gnome <= 0.4.26
Recommends: xzquiltrpm-python

**Comment by vuntz** [comment]
We just need to update to the right version. Done that in https://build.opensuse.org/request/show/831034
(leaving this issue open until the request gets accepted)

**Comment by vuntz** [comment]
Maintenance request was accepted
