### ISSUE TITLE
plugin is not compatible to osc 1.x

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-collab#60]
Running osc collab with osc 1.0 results in

```
> osc collab
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/osc-plugins/osc-collab.py", line 3958, in do_collab
    _osc_collab_alias = self.lastcmd[0]
AttributeError: 'Osc' object has no attribute 'lastcmd'
```

**Comment by DimStar77** [comment]
https://github.com/openSUSE/osc-plugin-collab/pull/61 makes it at least workable again (giving up on `osc gnome` as possible command. That's pure legacy anyway and technically still works, just command help will always refer to collab)
